### ISSUE TITLE
Condition of winning makes no sense

### ISSUE THREAD

**Issue by mayisa87** [Layusmen/ProjectHangman#3]
https://github.com/Layusmen/ProjectHangman/blob/41b324ee2ca669a00fc4b098f0daaec077726526/Hangman/Program.cs#L60

Currently you store all already guessed letters to a string. So this could look like "azevf" ;) so it won't be possible to check if this guessedLetters string contains the secretWord. This could only work id the whole word would be stored in your variable like

So you will need to think about another way to store
- your Placeholders
- and the right guessed letters

As you should output each iteration the alreasy right guessed letters, it makes sense to store somewhere the currenr game state.

For example i you got the word "help" the user should see first
_ _ _ _ 
If he guesses an e
_ e _ _

A list is a pretty comfortable way to store things and the good thing about it is, that you can access the stored value by their index.

Hint: You can iterate through an string by index too, so you can find out the position of a matching letter

**Comment by Layusmen** [comment]
Can you explain further on this. Or check my code again if I get you right.

**Comment by mayisa87** [comment]
Can be closed after working with new code base
