### ISSUE TITLE
Decide which counter to use and delete the other one

### ISSUE THREAD

**Issue by mayisa87** [Layusmen/ProjectHangman#8]
https://github.com/Layusmen/ProjectHangman/blob/7c9bc7c6aaa38bc6d787c6f8ffe68990390c2eb9/Hangman/Program.cs#L57-L58

Currently you got two counting variables, you should decided which one to use and remove the other one. From my point of view it would be enough to have the guessLeft counter, starting at MAX_GUESS, as you can change the while loop condition to loop as long as guessLeft is not 0.

**Comment by Layusmen** [comment]
I do not seem to understand this. Please can you expantiate?
